apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot2-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot2
  template:
    metadata:
      labels:
        app: heybot2
    spec:
      containers:
        - name: heybot2
          image: ghcr.io/aiboosts/heybot2.0-with-trivy-output:latest
          ports:
            - containerPort: 7861
          # command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET
      imagePullSecrets:
        - name: ghcr-secret  # Das ImagePullSecret, das du vorher erstellt hast
